name: "Pull Request Labeler"

# this will fail if we ever allow PRs from forks
# see: https://github.com/actions/labeler?tab=readme-ov-file#recommended-permissions
on:
  - pull_request

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: labels
        uses: actions/labeler@v5
        with:
          sync-labels: true
  static-analysis:
    needs: labeler
    uses: ./.github/workflows/static_analysis.yml
