---
name: "Static Analysis"

on:
  workflow_call:
    inputs: {}

permissions:
  contents: read

jobs:
  kustomize:
    if: contains(github.event.pull_request.labels.*.name, 'argocd')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git show HEAD
